janela = tk.Tk()
janela.title("Trabalho de APC")
janela.geometry("320x280")
tk.Label(janela, text="Recorte D: infraestrutura e condições dos domicilios").pack(pady=1)
tk.Label(janela, text=f"moradores: {qtd_linhasm} - domicilios: {qtd_linhasd}").pack(pady=1)
selecionado = tk.StringVar(value="Escolha a região")
option_menu = tk.OptionMenu(janela, selecionado, *meu_dicionario.keys())
option_menu.pack(pady=1)
btn_show = tk.Button(janela, text="Confirmar", command=grafico)
btn_show.pack(pady=1)
exp = btn_exportar = tk.Button(janela, text="Exportar dados", command=exportar)
exp.pack(pady=1)
janela.mainloop()